src/Entity/Task.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TaskRepository")
 */
class Task
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $deadline;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="created_tasks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $created_by;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=55)
     * @Assert\NotBlank()
     * @Assert\Length(min=3,max=50)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Field", mappedBy="task", orphanRemoval=true)
     */
    private $fields;

    /**
     * @ORM\Column(type="smallint")
     */
    private $priority;

    /**
     * @ORM\Column(type="smallint")
     */
    private $nb_answer_needed;

    /**
     * @ORM\Column(type="string", length=2)
     */
    private $language;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Assignment", mappedBy="task", orphanRemoval=true)
     */
    private $assignments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Content", mappedBy="task", orphanRemoval=true)
     */
    private $contents;

    /**
     * @ORM\Column(type="smallint")
     */
    private $status = 0;

    public function __construct()
    {
        $this->fields = new ArrayCollection();
        $this->assignments = new ArrayCollection();
        $this->contents = new ArrayCollection();
    }


    public function getId()
    {
        return $this->id;
    }

    public function getDeadline(): ?\DateTimeInterface
    {
        return $this->deadline;
    }

    public function setDeadline(\DateTimeInterface $deadline): self
    {
        $this->deadline = $deadline;

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->created_by;
    }

    public function setCreatedBy(?User $created_by): self
    {
        $this->created_by = $created_by;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Field[]
     */
    public function getFields(): Collection
    {
        return $this->fields;
    }

    public function addField(Field $field): self
    {
        if (!$this->fields->contains($field)) {
            $this->fields[] = $field;
            $field->setTask($this);
        }

        return $this;
    }

    public function removeField(Field $field): self
    {
        if ($this->fields->contains($field)) {
            $this->fields->removeElement($field);
            // set the owning side to null (unless already changed)
            if ($field->getTask() === $this) {
                $field->setTask(null);
            }
        }

        return $this;
    }

    public function getPriority(): ?int
    {
        return $this->priority;
    }

    public function setPriority(int $priority): self
    {
        $this->priority = $priority;

        return $this;
    }

    public function getNbAnswerNeeded(): ?int
    {
        return $this->nb_answer_needed;
    }

    public function setNbAnswerNeeded(int $nb_answer_needed): self
    {
        $this->nb_answer_needed = $nb_answer_needed;

        return $this;
    }

    public function getLanguage(): ?string
    {
        return $this->language;
    }

    public function setLanguage(string $language): self
    {
        $this->language = $language;

        return $this;
    }

    /**
     * @return Collection|Assignment[]
     */
    public function getAssignments(): Collection
    {
        return $this->assignments;
    }

    public function addAssignment(Assignment $assignment): self
    {
        if (!$this->assignments->contains($assignment)) {
            $this->assignments[] = $assignment;
            $assignment->setTask($this);
        }

        return $this;
    }

    public function removeAssignment(Assignment $assignment): self
    {
        if ($this->assignments->contains($assignment)) {
            $this->assignments->removeElement($assignment);
            // set the owning side to null (unless already changed)
            if ($assignment->getTask() === $this) {
                $assignment->setTask(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Content[]
     */
    public function getContents(): Collection
    {
        return $this->contents;
    }

    public function addContent(Content $content): self
    {
        if (!$this->contents->contains($content)) {
            $this->contents[] = $content;
            $content->setTask($this);
        }

        return $this;
    }

    public function removeContent(Content $content): self
    {
        if ($this->contents->contains($content)) {
            $this->contents->removeElement($content);
            // set the owning side to null (unless already changed)
            if ($content->getTask() === $this) {
                $content->setTask(null);
            }
        }

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }





}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;


/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements AdvancedUserInterface, \Serializable
{

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $last_name;

    /**
     * @var array
     *
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\Column(type="smallint")
     */
    private $nb_failed_connexion;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Task", mappedBy="created_by")
     */
    private $created_tasks;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Assignment", mappedBy="assigned_to", orphanRemoval=true)
     */
    private $assignedAssignments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Assignment", mappedBy="validated_by")
     */
    private $validatedAssignments;



    public function __construct()
    {
        $this->created_tasks = new ArrayCollection();
        $this->assignedAssignments = new ArrayCollection();
        $this->validatedAssignments = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    /**
     * Returns the roles or permissions granted to the user for security.
     */
    public function getRoles(): array
    {
        $roles = $this->roles;

        // guarantees that a user always has at least one role for security
        if (empty($roles)) {
            $roles[] = 'ROLE_USER';
        }

        return array_unique($roles);
    }

    public function setRoles(array $roles): void
    {
        $this->roles = $roles;
    }

    public function getNbFailedConnexion(): ?int
    {
        return $this->nb_failed_connexion;
    }

    public function setNbFailedConnexion(int $nb_failed_connexion): self
    {
        $this->nb_failed_connexion = $nb_failed_connexion;

        return $this;
    }
    public function addNbFailedConnexion(): self
    {
        $this->nb_failed_connexion++;

        return $this;
    }
    public function razNbFailedConnexion(): self
    {
        $this->nb_failed_connexion = 0;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Task[]
     */
    public function getCreatedTasks(): Collection
    {
        return $this->created_tasks;
    }

    public function addCreatedTask(Task $createdTask): self
    {
        if (!$this->created_tasks->contains($createdTask)) {
            $this->created_tasks[] = $createdTask;
            $createdTask->setCreatedBy($this);
        }

        return $this;
    }

    public function removeCreatedTask(Task $createdTask): self
    {
        if ($this->created_tasks->contains($createdTask)) {
            $this->created_tasks->removeElement($createdTask);
            // set the owning side to null (unless already changed)
            if ($createdTask->getCreatedBy() === $this) {
                $createdTask->setCreatedBy(null);
            }
        }

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }




    public function getSalt()
    {
        // you *may* need a real salt depending on your encoder
        // see section on salt below
        return null;
    }

    public function eraseCredentials()
    {
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,
            $this->active,
            // see section on salt below
            // $this->salt,
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->username,
            $this->password,
            $this->active,
            // see section on salt below
            // $this->salt
            ) = unserialize($serialized, ['allowed_classes' => false]);
    }

    public function isAccountNonExpired()
    {
        return true;
    }

    public function isAccountNonLocked()
    {
        return ($this->nb_failed_connexion <= 3);
    }

    public function isCredentialsNonExpired()
    {
        return true;
    }

    public function isEnabled()
    {
        return $this->active;
    }

    /**
     * @return Collection|Assignment[]
     */
    public function getAssignments(): Collection
    {
        return $this->assignedAssignments;
    }

    public function addAssignment(Assignment $assignment): self
    {
        if (!$this->assignedAssignments->contains($assignment)) {
            $this->assignedAssignments[] = $assignment;
            $assignment->setUser($this);
        }

        return $this;
    }

    public function removeAssignment(Assignment $assignment): self
    {
        if ($this->assignedAssignments->contains($assignment)) {
            $this->assignedAssignments->removeElement($assignment);
            // set the owning side to null (unless already changed)
            if ($assignment->getUser() === $this) {
                $assignment->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Assignment[]
     */
    public function getValidatedAssignments(): Collection
    {
        return $this->validatedAssignments;
    }

    public function addValidatedAssignment(Assignment $validatedAssignment): self
    {
        if (!$this->validatedAssignments->contains($validatedAssignment)) {
            $this->validatedAssignments[] = $validatedAssignment;
            $validatedAssignment->setValidatedBy($this);
        }

        return $this;
    }

    public function removeValidatedAssignment(Assignment $validatedAssignment): self
    {
        if ($this->validatedAssignments->contains($validatedAssignment)) {
            $this->validatedAssignments->removeElement($validatedAssignment);
            // set the owning side to null (unless already changed)
            if ($validatedAssignment->getValidatedBy() === $this) {
                $validatedAssignment->setValidatedBy(null);
            }
        }

        return $this;
    }




}

src/Form/Type/TaskType.php
<?php

namespace App\Form\Type;

use Symfony\Component\Form\AbstractType;

use Symfony\Component\Form\FormBuilderInterface;

use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

use App\Entity\Feeling;

class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options){

        $builder
            ->add('name', TextType::class, [
                'label' => 'entity.Task.name'
            ])
            ->add('priority', ChoiceType::class, [
                'choices'  => [
                    'entity.Task.priority1' => 1,
                    'entity.Task.priority2' => 2,
                    'entity.Task.priority3' => 3,
                ],
                'data' => 2,
                'label' => 'entity.Task.priority'
            ])
            /*
            ->add('language', ChoiceType::class, [
                'choices'  => [
                    'menu.language.en' => 'en',
                    'menu.language.es' => 'es',
                    'menu.language.fr' => 'fr',
                ],
                'data' => 'en',
                'label' => 'menu.language.label'
            ])*/
            ->add('language', HiddenType::class, [
                'data'=>'en'
            ]) // pour l'instant on gère que les inputs en anglais
            ->add('deadline', DateType::class, [
                'label' => 'entity.Task.deadline',
                'data' => new \DateTime(date('Y-m-d',mktime(0,0,0,date('m'),date('d')+14,date('Y'))))
            ])
            ->add('nb_answer_needed', IntegerType::class, [
                'attr' => ['min' => 1],
                'label' => 'entity.Task.nb_answer_needed',
                'data' => 1
            ])
            ->add('file', CsvType::class, [
                'label' => 'dnd_file.file',
                'mapped' => false
            ])
            ->add('fields', FieldsType::class, [
                'class' => Feeling::class,
                'choice_label' => function ($f) {
                    return $f->getLabel();
                },
                'multiple' => true,
                'label' => 'entity.Field.labels',
                'mapped' => false
            ])
            ->add('save', SubmitType::class, [
                'label' => 'entity.Task.add'
            ]);

    }

}

templates/task/add.html.twig
{% extends 'layouts/admin.html.twig' %}

{% block title %}{{ 'entity.Task.label'|trans }}{% endblock %}

{% block content %}

    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}

    <div class="mpblock row">
        <h4>Todo : </h4>
        <div class="mpcontent">
            <ul>
                <li>Améliorer contrôle du csv <span class="label label-warning">todo</span></li>
                <li>Pouvoir créer un feeling <span class="label label-warning">todo</span></li>
            </ul>
        </div>
    </div>

{% endblock %}

templates/task/index.html.twig
{% extends 'layouts/site.html.twig' %}

{% block title %}{{ 'menu.tasks'|trans }}{% endblock %}

{% block content %}

    {% for flashMessage in app.session.flashbag.get('danger') %}
        <div class="alert alert-danger">{{ flashMessage|trans }}</div>
    {% endfor %}

    <div class="mpblock row">
        <h4>{{ 'entity.Task.ongoing_tasks'|trans }}</h4>
        <div class="mpcontent">
            {% if ongoingAssignments|length == 0 %}
                {{ 'entity.Task.none'|trans }}
            {%  else %}
                {% for row in ongoingAssignments %}
                    <div class="col-md-4 mpssblock">
                        <a class="mpcontent text-center" href="{{ path('fill_assignment', {id: row.0.id}) }}" title="{{ 'entity.Assignment.continue'|trans }}">
                            <h5>{{ row.0.task.name }}</h5>
                            <span>
                            <div class="progress progress-task mptooltype" data-toggle="tooltype">
                                <div id="barDone" class="progress-bar progress-bar-striped" role="progressbar" aria-valuenow="{{ row.nb_answers }}" aria-valuemax="{{ row.nb_fields*row.nb_contents }}"></div>
                            </div>
                            <div class="prio{{ row.0.task.deadline < "now"|date('Y-m-d') ? '1' : '0' }}">
                                <i class="fa fa-calendar" ></i>
                                <span>{{ 'entity.Task.deadline'|trans }} : {{ row.0.task.deadline|localizeddate('medium', 'none') }}</span>
                            </div>
                            <div class="prio{{ row.0.task.priority }}">
                                <i class="fa fa-clock-o" ></i>
                                <span>{{ 'entity.Task.priority'|trans }} : {{ ('entity.Task.priority'~row.0.task.priority)|trans }}</span>
                            </div>
                            <div>
                                <i class="fa fa-files-o" ></i>
                                <span>{{ 'entity.Assignment.nb_contents'|trans }} : {{ row.nb_contents }}</span>
                            </div>
                            <div>
                                <i class="fa fa-columns" ></i>
                                <span>{{ 'entity.Assignment.nb_fields'|trans }} : {{ row.nb_fields }}</span>
                            </div>
                        </a>

                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>

    <div class="mpblock row">
        <h4>{{ 'entity.Task.todo_tasks'|trans }}</h4>
        <div class="mpcontent">
            {% if nextTodoTasks |length == 0 %}
                {{ 'entity.Task.none'|trans }}
            {%  else %}
                {% for row in nextTodoTasks %}
                    <div class="col-md-4 mpssblock">
                        <a class="mpcontent text-center" href="{{ path('pick_task', {id: row.0.id}) }}" title="{{ 'entity.Task.pick'|trans }}">
                            <h5>{{ row.0.name }}</h5>

                            <div class="prio{{ row.0.deadline < "now"|date('Y-m-d') ? '1' : '0' }}">
                                <i class="fa fa-calendar" ></i>
                                <span>{{ 'entity.Task.deadline'|trans }} : {{ row.0.deadline|localizeddate('medium', 'none') }}</span>
                            </div>
                            <div class="prio{{ row.0.priority }}">
                                <i class="fa fa-clock-o" ></i>
                                <span>{{ 'entity.Task.priority'|trans }} : {{ ('entity.Task.priority'~row.0.priority)|trans }}</span>
                            </div>
                            <div>
                                <i class="fa fa-files-o" ></i>
                                <span>{{ 'entity.Assignment.nb_contents'|trans }} : {{ row.nb_contents }}</span>
                            </div>
                            <div>
                                <i class="fa fa-columns" ></i>
                                <span>{{ 'entity.Assignment.nb_fields'|trans }} : {{ row.nb_fields }}</span>
                            </div>

                        </a>
                    </div>
                {% endfor %}

            <div class="col-md-4 mpssblock">
                <div class="mpcontent text-center">
                    <p>{{ 'entity.Task.and_x_more'|trans({'%x%': (nbTodoTasks - nextTodoTasks|length)}) }}</p>
                </div>
            </div>
            {% endif %}
        </div>

    </div>

    <div class="mpblock row">
        <h4>Todo : </h4>
        <div class="mpcontent">
            <ul>
                <li>Liste tâche en cours <span class="label label-success">ok</span></li>
                <li>Liste d'attente <span class="label label-success">ok</span></li>
                <li>Pick tâche <span class="label label-success">ok</span></li>
                <li>Fill tâche <span class="label label-success">ok</span></li>
                <li>Afficher graphiques sur perf user <span class="label label-warning">todo</span></li>
            </ul>
        </div>
    </div>

{% endblock %}

templates/task/show.html.twig
{% extends 'layouts/admin.html.twig' %}

{% block title %}{{ 'entity.Task.label'|trans }} {{ task.name }}{% endblock %}

{% block content %}



    <div class="mpblock row">
        <h4>{{ 'show.info_gen'|trans }}</h4>
        <div class="mpcontent" id="task-gen">

            <h2>
                <span>Tâche {{ task.name }}</span>
                {% if is_granted('ROLE_ADMIN') %}
                    <i class="fa fa-edit fa-clickme" title="{{ 'form.edit'|trans }}"></i>
                {% endif %}
            </h2>
            <div class="row">
                <div class="col-md-6">
                    <strong>{{ 'entity.Task.created_by'|trans }} : </strong>
                    <span><i class="fa fa-user"></i> {{ task.createdBy.firstName }} {{ task.createdBy.lastName }} <i class="fa fa-calendar"></i> {{ task.createdAt|date('Y-m-d h:i:s') }}</span>
                </div>
                <div class="col-md-6">

                </div>
            </div>
            <div class="row">
                <div class="col-md-6">

                    <div class="mpRead">
                        <div class="prio{{ task.deadline < "now"|date('Y-m-d') ? '1' : '0' }}">
                            <i class="fa fa-calendar" ></i>
                            <span>{{ 'entity.Task.deadline'|trans }} : {{ task.deadline|localizeddate('medium', 'none') }}</span>
                        </div>
                        <div class="prio{{ task.priority }}">
                            <i class="fa fa-clock-o" ></i>
                            <span>{{ 'entity.Task.priority'|trans }} : {{ ('entity.Task.priority'~task.priority)|trans }}</span>
                        </div>
                    </div>

                    {{ form_start(form, {'action' : path('updAjax_task'), 'data-id' : task.id, 'attr':{'class':'mpWrite d-none'}}) }}

                    {{ form_end(form) }}

                </div>
                <div class="col-md-6">
                    <div>
                        <i class="fa fa-files-o" ></i>
                        <span>{{ 'entity.Assignment.nb_contents'|trans }} : {{ task.contents|length }}</span>
                    </div>
                    <div>
                        <i class="fa fa-columns" ></i>
                        <span>{{ 'entity.Assignment.nb_fields'|trans }} : {{ task.fields|length }}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="mpblock row">
        <h4>{{ 'entity.Answer.list'|trans }} <i onclick="console.log('todo');" class="fa fa-csv fa-clickme" title="{{ 'list.download'|trans }}"></i></h4>
        <div class="mpcontent">
            <table id="tokenedit" class="mpstandard mp-table-ajax" data-url="{{ path('token_edit') }}">
                <thead>
                <tr>
                    <th>{{ 'entity.Content.label'|trans }}</th>
                    <th>{{ 'entity.Field.label'|trans }}</th>
                    {% for assignment in task.assignments %}
                        <th>
                            <i class="fa fa-user {{ icones[assignment.status] }}" title="{{ ('entity.Assignment.status'~assignment.status)|trans }}"></i>
                            {{ assignment.assignedTo.firstName }} {{ assignment.assignedTo.lastName }}
                        </th>
                    {% endfor %}
                </tr>
                </thead>
                <tbody>
                {% for row in tbl %}
                    <tr data-content="{{ row.content_id }}" data-field="{{ row.field_id }}">
                        <td>{{ row.content }}</td>
                        <td>{{ row.feeling }}</td>
                        {% for assignment in task.assignments %}
                            <td data-obj="answer" data-assignment="{{ assignment.id }}" data-answer="{{ row['answer_id'~assignment.id] }}">{{ row['answer'~assignment.id] }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>


    <div class="mpblock row">
        <h4>Todo : </h4>
        <div class="mpcontent">
            <ul>
                <li>refaire entete avec deadline et priority editable : <span class="label label-info">todo</span></li>
                <li>refaire tableau avec filtre, tri, pagination : <span class="label label-info">todo</span></li>
                <li>telecharger csv : <span class="label label-info">todo</span></li>
            </ul>
        </div>
    </div>




{% endblock %}